repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.10
  hooks:
  - id: ruff-check
    args: ["--fix"]
  - id: ruff-format
- repo: https://github.com/python-poetry/poetry
  rev: "1.5.1"
  hooks:
  - id: poetry-check
  - id: poetry-lock
    files: "^(pyproject.toml|poetry.lock)$"
