name: "Publish artifacts"

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
on:
  release:
    types: [published]
  workflow_dispatch:

env:
  POETRY_VERSION: "1.2.2"

jobs:
  build:
    name: Build and upload artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1
        # with:
        #   version: ${{ env.POETRY_VERSION }}

      - name: Build package
        run: |
          make build

      - name: Attach artifact to release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry install --only ci
          ARTIFACT_FILE_PATH=$(ls -d -1 ./dist/*.whl)
          poetry run python tools/upload_artifacts.py \
            --github-token "${GITHUB_TOKEN}" \
            --tag "${GITHUB_REF_NAME}" \
            --artifact "${ARTIFACT_FILE_PATH}"

      - name: Publish package to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi ${PYPI_TOKEN}
          poetry publish
